# -*- coding: utf-8 -*-
"""appy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ITFne6A0KxlOxju4ZPa3RqLcy9ogK8QZ
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from flask import Flask, render_template, request, Markup
import numpy as np
import pickle 




# Loading crop recommendation model

crop_recommendation_model_path = 'RandomForest.pkl'
crop_recommendation_model = pickle.load(
    open(crop_recommendation_model_path, 'rb'))


app = Flask(__name__)

@ app.route('/crop-recommend')
def crop_recommend():
    title = 'Harvestify - Crop Recommendation'
    return render_template('crop.html', title=title)


@ app.route('/crop-predict', methods=['POST'])
def crop_prediction():
    title = 'Harvestify - Crop Recommendation'
    return render_template('crop.html', title=title)